src/web-layout-portal/Models/ErrorViewModel.cs
using System;

namespace web_layout_portal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/web-layout-portal/Components/ViewPortViewComponent.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace web_layout_portal.Components
{
    public class ViewPortViewComponent : ViewComponent
    {

        public async Task<IViewComponentResult> InvokeAsync(string name)
        {
            return new RemoteViewResult(name);
 
        }
    }

    public class RemoteViewResult : IViewComponentResult
    {
        private readonly string _name;
        HttpClient _client = new HttpClient()
        {
            BaseAddress = new Uri("http://localhost:5001/")
        };

        public RemoteViewResult(string name)
        {
            _name = name;
        }

        public void Execute(ViewComponentContext context)
        {
            ExecuteAsync(context).Wait();
        }

        public async Task ExecuteAsync(ViewComponentContext context)
        {
            var data = await _client.GetStringAsync(_name);
            await context.Writer.WriteAsync(data);
        }
    }
}

src/web-layout-portal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using web_layout_portal.Models;

namespace web_layout_portal.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/web-layout-portal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
@await Component.InvokeAsync("ViewPort", new { name = "Home/Privacy" })

src/web-layout-portal/Views/Shared/_Layout.bak.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - web_layout_portal</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" /> 
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">web_layout_portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - web_layout_portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/web-layout-portal/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PCF Sample App</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <meta name="apple-mobile-web-app-capable" content="yes" />

    <script src="~/js/jquery.min.js" type="text/javascript"></script>
    <script src="~/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/js/morris.min.js" type="text/javascript"></script>
    <script src="~/js/raphael-min.js" type="text/javascript"></script>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/morris.css" rel="stylesheet" />

    <style>
        .navbar.navbar-inverse.navbar-fixed-top {
            background-color: #3EB0FF;
        }

        .navbar-inverse .navbar-brand {
            color: #04050b;
        }

        .nav.navbar-nav li a {
            color: #04050b;
        }

        .dropdown-toggle {
            color: #04050b;
        }

        .table-fixed thead {
            width: 97%;
        }

        .table-fixed tbody {
            height: 160px;
            overflow-y: auto;
            width: 100%;
        }

        .table-fixed thead, .table-fixed tbody, .table-fixed tr, .table-fixed td,
        .table-fixed th {
            display: block;
        }

            .table-fixed tbody td, .table-fixed thead > tr > th {
                float: left;
                border-bottom-width: 0;
            }
    </style>

</head>


<body>

<!-- ++++++++++ -->
<!-- Navigation -->
<!-- ++++++++++ -->

<nav th:fragment="navigation"
     class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span
                    class="icon-bar">
                </span> <span class="icon-bar"></span>
                <span
                    class="icon-bar">
                </span>
            </button>
            <a class="navbar-brand" href="./">
                <img
                    src="/images/icon_cf_green.png"
                    style="width: 40px; height: 40px; margin-top: -15px;"/>&nbsp;
                Cloud Foundry Basic Demo
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse"
             id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="basics">Scale &amp; HA</a>
                </li>
                <li>
                    <a href="services">Services</a>
                </li>
                <li>
                    <a href="bluegreen">Blue Green</a>
                </li>
                @if (ViewBag.HasEurekaBinding)
                {
                    <li>
                        <a href="eureka">Service Discovery</a>
                    </li>
                }
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

@RenderBody()


<!-- ++++++ -->
<!-- FOOTER -->
<!-- ++++++ -->
<footer th:fragment="footer" class="footer">
    <div class="container">
        <p class="text-muted">Provided to you by Pivotal!</p>
    </div>
</footer>

<!-- Scripts -->
<script th:fragment="app-instance-script">
    $(function() {

        var url = '/tutorial';
        if ($('#tutorialName').text() !== undefined) {
            url = '/tutorial/' + $('#tutorialName').text();
        } else {
            url = '/tutorial/index';
        }

        $("#description").load(url + "-desc.html");
        $("#demonstration").load(url + "-demo.html");
    });
</script>


</body>

</html>